# Generated by Django 3.2.11 on 2022-01-05 10:49

from django.db import migrations
from ..models import CarStatusConstants

def populate_car_status(apps, schema_editor):
    CarStatus = apps.get_model("company", "CarStatus")
    active = CarStatus(id=CarStatusConstants.ACTIVE_ID, name='Active')
    active.save()
    out_of_service = CarStatus(id=CarStatusConstants.OUT_OF_SERVICE_ID, name='Out of service')
    out_of_service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_car_status)
    ]
