# Generated by Django 3.2.11 on 2022-01-05 09:41

from django.db import migrations

def populate_car_status(apps, schema_editor):
    CarStatus = apps.get_model("company", "CarStatus")
    active = CarStatus(id=1, name='Active')
    active.save()
    out_of_service = CarStatus(id=2, name='Out of service')
    out_of_service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220105_0935'),
    ]

    operations = [
        migrations.RunPython(populate_car_status)
    ]
