# Generated by Django 4.0 on 2022-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_office_id_office_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
