# Generated by Django 4.0.1 on 2022-01-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_carstatuschangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstatuschangelog',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='company.car'),
        ),
    ]
